/** Barrel re-exports for the Charts feature (spec, SQL, ECharts options). */
export {
  CHART_MAX_ROWS,
  CHART_SPEC_VERSION,
  DEFAULT_BAR_TOP_N,
  DEFAULT_HISTOGRAM_BINS,
  createDefaultChartSpec,
  getCategoryColumnNames,
  getColumnCardinality,
  getColumnIsInteger,
  getColumnSemanticType,
  getDefaultCategoryColumn,
  getDefaultScatterColumns,
  getFilterColumnNames,
  getNumericColumnNames,
  getSplitColumnNames,
  getTemporalColumnNames,
  getTemporalKind,
  isBarCountOnly,
  isBucketableTemporalColumn,
  isCategoryColumn,
  normalizeChartSpec,
  sortColumnNamesAsc,
  validateChartSpec,
  type ChartAggregation,
  type ChartBucket,
  type ChartDataPoint,
  type ChartFilter,
  type ChartFilterOperator,
  type ChartReferenceLine,
  type ChartSpec,
  type ChartType,
  type ChartValidation,
  type ChartYAxisScale,
} from '@/features/charts/chartSpec'

export {
  buildBarChartSql,
  buildChartSql,
  buildHistogramChartSql,
  buildLineChartSql,
  buildScatterChartSql,
} from '@/features/charts/chartSql'

export {
  buildBarChartOption,
  buildChartOption,
  buildHistogramChartOption,
  buildLineChartOption,
  buildScatterChartOption,
  queryResultToChartData,
} from '@/features/charts/chartOptions'
